services:

  mysql:
    image: mysql:8.0
    container_name: lab_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: orders_db
      MYSQL_USER: app
      MYSQL_PASSWORD: app_password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot_password"]
      interval: 5s
      timeout: 5s
      retries: 20
    networks:
      - lab_net

  kafka:
    image: apache/kafka:3.7.0
    container_name: lab_kafka
    environment:
      KAFKA_NODE_ID: 0
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:29092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 0@kafka:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
    ports:
      - "29092:29092"
    volumes:
      - kafka_data:/var/lib/kafka/data
    healthcheck:
      test: ["CMD-SHELL", "/opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --list || exit 1"]
      interval: 5s
      timeout: 10s
      retries: 20
    networks:
      - lab_net

  kafka-init:
    image: apache/kafka:3.7.0
    container_name: lab_kafka_init
    depends_on:
      kafka:
        condition: service_healthy
    entrypoint: ["/bin/bash", "-c"]
    command:
      - |
        /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9092 \
          --create --if-not-exists \
          --topic order-events \
          --partitions 3 \
          --replication-factor 1
        echo "--- topics after create ---"
        /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9092 --list
        /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9092 --describe --topic order-events
    networks:
      - lab_net

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: lab_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbit_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 10s
      retries: 20
    networks:
      - lab_net

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: lab_kafka_ui
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    ports:
      - "8080:8080"
    networks:
      - lab_net

  api:
    build:
      context: ./flask-app
    container_name: lab_api
    depends_on:
      mysql:
        condition: service_healthy
      kafka-init:
        condition: service_completed_successfully
      rabbitmq:
        condition: service_healthy
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: "3306"
      MYSQL_DB: orders_db
      MYSQL_USER: app
      MYSQL_PASSWORD: app_password
      KAFKA_BOOTSTRAP: kafka:9092
      RABBIT_HOST: rabbitmq
      RABBIT_PORT: "5672"
      RABBIT_USER: guest
      RABBIT_PASS: guest
    networks:
      - lab_net

  nginx:
    image: nginx:1.27-alpine
    container_name: lab_nginx
    depends_on:
      - api
    ports:
      - "80:80"
    volumes:
      - ./html:/usr/share/nginx/html:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - lab_net

  consumer-payment:
    build:
      context: ./kafka
    container_name: lab_consumer_payment
    depends_on:
      kafka-init:
        condition: service_completed_successfully
    environment:
      KAFKA_BOOTSTRAP: kafka:9092
    command: ["python", "payment_consumer.py"]
    networks:
      - lab_net

  consumer-shipping:
    build:
      context: ./kafka
    container_name: lab_consumer_shipping
    depends_on:
      kafka-init:
        condition: service_completed_successfully
    environment:
      KAFKA_BOOTSTRAP: kafka:9092
    command: ["python", "delivery_consumer.py"]
    networks:
      - lab_net

  notification-worker:
    build:
      context: ./rabbit
    container_name: lab_notification_worker
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      RABBIT_HOST: rabbitmq
      RABBIT_PORT: "5672"
      RABBIT_USER: guest
      RABBIT_PASS: guest
    networks:
      - lab_net


volumes:
  mysql_data:
  kafka_data:
  rabbit_data:

networks:
  lab_net:
    driver: bridge